server:
  port: 9600
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /uav/ops
spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  application:
    name: uav-ops
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
swagger:
    enable: true
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100

